<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ASHKOL" failures="1" tests="1" name="api.tests.AccessTokenTests" time="0.517" errors="0" timestamp="2025-09-01T23:46:16 IST" skipped="0">
  <testcase classname="api.tests.AccessTokenTests" name="getAccessToken" time="0.517">
    <failure message="expected [BQCvf68JsKrt2ucx2DjwY0dC--VFV89yq_Wu2G8JBVZ_KvouzwSIyiTFB8X25IpNAdQMKvpibQKoulha1veYyY70ce-B9Sl5JvSTwEV-M8GxQBoU3POOQcPG3LVqn9NVBw1bDnrm9EI] but found [BQC0e5u7k5jf6RYZBwuneFSvQ94P0KykW2b_WMzY-lPvx38Oo4F3Ku7x4KP_G7Mcl_FBH2ltGoCovg22BjCgakt1G2W2a4Q71q6sNY-GnPtMuxbwiqlCE31pTT0PP8O6Ga266XHOYaA]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [BQCvf68JsKrt2ucx2DjwY0dC--VFV89yq_Wu2G8JBVZ_KvouzwSIyiTFB8X25IpNAdQMKvpibQKoulha1veYyY70ce-B9Sl5JvSTwEV-M8GxQBoU3POOQcPG3LVqn9NVBw1bDnrm9EI] but found [BQC0e5u7k5jf6RYZBwuneFSvQ94P0KykW2b_WMzY-lPvx38Oo4F3Ku7x4KP_G7Mcl_FBH2ltGoCovg22BjCgakt1G2W2a4Q71q6sNY-GnPtMuxbwiqlCE31pTT0PP8O6Ga266XHOYaA]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at api.tests.AccessTokenTests.getAccessToken(AccessTokenTests.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- getAccessToken -->
</testsuite> <!-- api.tests.AccessTokenTests -->
